security:
    encoders:
        Res\BackendBundle\Entity\AdminUser: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_user:
            entity: { class: Res\BackendBundle\Entity\AdminUser, property: username }
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ]}

    firewalls:
        admin:
            pattern: ^/bo
            provider: admin_user
            anonymous:  ~
            form_login:
                login_path: /bo/login
                check_path: /bo/login_check
                default_target_path: /bo
                always_use_default_target_path: true
            logout:
                path: /bo/logout

    access_control:
        - { path: ^/bo/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
